import Head from "next/head"
import Image from "next/image"
import { Inter } from "next/font/google"
import LoginForm from "@/components/Login/LoginForm"
import NavBar from "../components/Layout/NavBar"
import { Container, Row } from "reactstrap"
import styles from "@/styles/Home.module.scss"

const inter = Inter({ subsets: ["latin"] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main>
        <Row className='mb-3'>
          <NavBar />
        </Row>
        <Row>
          <Container className={styles.appContainer}>
            <LoginForm />
          </Container>
        </Row>
      </main>
    </>
  )
}
