import normalizeTime from './normalizeTime'

describe('normalizations', () => {
  describe('normalizeTime', () => {
    it('exists', () => expect(normalizeTime).toBeDefined())

    it('null', () => {
      expect(normalizeTime('')).toBe('')
      expect(normalizeTime()).toBe(undefined)
    })

    it('hours only', () => {
      expect(normalizeTime('0')).toBe('12:00 AM')
      expect(normalizeTime('1')).toBe('1:00 AM')
      expect(normalizeTime('2')).toBe('2:00 AM')
      expect(normalizeTime('3')).toBe('3:00 AM')
      expect(normalizeTime('4')).toBe('4:00 AM')
      expect(normalizeTime('5')).toBe('5:00 AM')
      expect(normalizeTime('6')).toBe('6:00 AM')
      expect(normalizeTime('7')).toBe('7:00 AM')
      expect(normalizeTime('8')).toBe('8:00 AM')
      expect(normalizeTime('9')).toBe('9:00 AM')
      expect(normalizeTime('10')).toBe('10:00 AM')
      expect(normalizeTime('11')).toBe('11:00 AM')
      expect(normalizeTime('12')).toBe('12:00 PM')
      expect(normalizeTime('13')).toBe('1:00 PM')
      expect(normalizeTime('14')).toBe('2:00 PM')
      expect(normalizeTime('15')).toBe('3:00 PM')
      expect(normalizeTime('16')).toBe('4:00 PM')
      expect(normalizeTime('17')).toBe('5:00 PM')
      expect(normalizeTime('18')).toBe('6:00 PM')
      expect(normalizeTime('19')).toBe('7:00 PM')
      expect(normalizeTime('20')).toBe('8:00 PM')
      expect(normalizeTime('21')).toBe('9:00 PM')
      expect(normalizeTime('22')).toBe('10:00 PM')
      expect(normalizeTime('23')).toBe('11:00 PM')
      expect(normalizeTime('24')).toBe('12:00 AM')

      expect(normalizeTime('0')).toBe('12:00 AM')
      expect(normalizeTime('00')).toBe('12:00 AM')
    })

    it('hours with minutes', () => {
      expect(normalizeTime('1:23')).toBe('1:23 AM')
      expect(normalizeTime('13:23')).toBe('1:23 PM')

      expect(normalizeTime('12:23')).toBe('12:23 PM')
      expect(normalizeTime('0:00')).toBe('12:00 AM')
      expect(normalizeTime('24:00')).toBe('12:00 AM')
    })

    it('hours and am/pm only', () => {
      expect(normalizeTime('1pm')).toBe('1:00 PM')
      expect(normalizeTime('1 pm')).toBe('1:00 PM')
      expect(normalizeTime('1am')).toBe('1:00 AM')
      expect(normalizeTime('1 am')).toBe('1:00 AM')
      expect(normalizeTime('1PM')).toBe('1:00 PM')
      expect(normalizeTime('1 PM')).toBe('1:00 PM')
      expect(normalizeTime('1AM')).toBe('1:00 AM')
      expect(normalizeTime('1 AM')).toBe('1:00 AM')
      expect(normalizeTime('0am')).toBe('12:00 AM')

      expect(normalizeTime('1p')).toBe('1:00 PM')
      expect(normalizeTime('1 p')).toBe('1:00 PM')
      expect(normalizeTime('1a')).toBe('1:00 AM')
      expect(normalizeTime('1 a')).toBe('1:00 AM')
      expect(normalizeTime('1P')).toBe('1:00 PM')
      expect(normalizeTime('12 P')).toBe('12:00 PM')
      expect(normalizeTime('1A')).toBe('1:00 AM')
      expect(normalizeTime('24 A')).toBe('12:00 AM')
      expect(normalizeTime('0a')).toBe('12:00 AM')
    })

    it('hundred hours', () => {
      expect(normalizeTime('1200')).toBe('12:00 PM')
      expect(normalizeTime('1230')).toBe('12:30 PM')
      expect(normalizeTime('2400')).toBe('12:00 AM')
      expect(normalizeTime('2422')).toBe('2422')
      expect(normalizeTime('100')).toBe('1:00 AM')
      expect(normalizeTime('50')).toBe('12:50 AM')
      expect(normalizeTime('75')).toBe('1:15 AM')
      expect(normalizeTime('150')).toBe('1:50 AM')
      expect(normalizeTime('400')).toBe('4:00 AM')
      expect(normalizeTime('425')).toBe('4:25 AM')
      expect(normalizeTime('2215')).toBe('10:15 PM')
      expect(normalizeTime('115')).toBe('1:15 AM')
      expect(normalizeTime('2015')).toBe('8:15 PM')
      expect(normalizeTime('2215')).toBe('10:15 PM')
      expect(normalizeTime('25')).toBe('12:25 AM')
    })

    it('bad data', () => {
      expect(normalizeTime('-1')).toBe('1:00 AM')
      expect(normalizeTime('ashdhjsd')).toBe('ashdhjsd')
      expect(normalizeTime('-25')).toBe('12:25 AM')
      expect(normalizeTime('12:asd')).toBe('12:00 AM')
      expect(normalizeTime('12:34as')).toBe('12:34 AM')
      expect(normalizeTime(':34as')).toBe('12:34 AM')
      expect(normalizeTime(':34')).toBe('12:34 AM')
      expect(normalizeTime(':34 pm')).toBe('12:34 PM')
      expect(normalizeTime('13:34 AM')).toBe('1:34 AM')
      expect(normalizeTime('13:34as AM')).toBe('1:34 AM')
      expect(normalizeTime('      @#$*&(#$*::::#$')).toBe('      @#$*&(#$*::::#$')
      expect(normalizeTime(':')).toBe(':')
    })

    it('other cases', () => {
      expect(normalizeTime('dude the time is: 3 PM now')).toBe('3:00 PM')
      expect(normalizeTime('dude the time is: 3:00 PM now')).toBe('3:00 PM')
      expect(normalizeTime('5:751 AM')).toBe('5:751 AM')
      expect(normalizeTime('751:7867 AM')).toBe('751:7867 AM')
      expect(normalizeTime('751:7867')).toBe('751:7867')
      expect(normalizeTime('5:751')).toBe('5:751')
      expect(normalizeTime('5:75')).toBe('5:75')
      expect(normalizeTime('5:61')).toBe('5:61')
      expect(normalizeTime('5:60')).toBe('5:60')
      expect(normalizeTime('1p.m.')).toBe('1:00 PM')
      expect(normalizeTime('1x')).toBe('1:00 AM')
      expect(normalizeTime('1xm')).toBe('1:00 AM')
      expect(normalizeTime('11:1')).toBe('11:01 AM')
      expect(normalizeTime('1:100')).toBe('1:100')
      expect(normalizeTime('foo bar 1 PM dude')).toBe('1:00 PM')
    })
  })
})
